org: j41r0
service: CrudProject001

provider:
  name: aws
  runtime: nodejs20.x

functions:
  patientsCreate:
    handler: src/patients/functions/create.handler
    events:
      - http:
          method: POST
          path: patients

resources:
  Resources:
    patientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Patients 
        AttributeDefinitions:
          - AttributeName: PK #taxId
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
