# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: j41r0
# "service" is the name of this project. This will also be added to your AWS resource names.
service: CrudProject001

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

recources:
  Recources:
    patientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Patient 
        AttributeDefinitions:
          - AttributeName: PK #taxId
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        OnDemandThroughput:
          MaxReadCapacityUnits: 5
          MaxWriteCapacityUnits: 5
